#!/bin/bash
#
# bootstrap installs things.

DOTFILES_SCRIPTS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DOTFILES_ROOT="$DOTFILES_SCRIPTS/.."

set -e

echo ''

info () {
  printf "\033[00;34m$1\033[0m\n"
}

user () {
  printf "\033[0;33m$1\033[0m: "
}

success () {
  printf "\033[00;32m$1\033[0m\n"
}

fail () {
  printf "\n\033[2K[\033[0;31mX\033[0m] $1\n"
  exit
}

function_exists() {
  declare -f -F $1 > /dev/null
  return $?
}

install_homebrew () {
  # If we are on a mac, lets install and setup homebrew
  if [ "$(uname -s)" == "Darwin" ]
  then

    # XCode is a pre-requisite, if you hit this you didn't follow instructions
    if ! [ -e /Applications/Xcode.app ]
    then
      open macappstores://itunes.apple.com/us/app/xcode/id497799835?mt=12

      fail "You must install Xcode before bootstrapping"
    fi

    # Check for Homebrew
    if test ! $(which brew)
    then
      info 'Installing homebrew'

      ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
    fi

    info 'Updating homebrew'

    brew update

    brew install git
  fi
}

install_prereqs() {
  mkdir -p /usr/local/git/contrib/completion/
  curl https://raw.github.com/git/git/master/contrib/completion/git-completion.bash -o /usr/local/git/contrib/completion/git-completion.bash
  curl https://raw.github.com/git/git/master/contrib/completion/git-prompt.sh -o /usr/local/git/contrib/completion/git-prompt.sh
}

install_dotfiles () {
  info "Cloning dotfiles repository"

  git clone git://github.com/mikekavouras/dotfiles.git ~/.dotfiles
}

install_homebrew

if ! [ -e ~/.dotfiles ]
then
  install_dotfiles
fi

for source in `find $DOTFILES_SCRIPTS -maxdepth 1 -name setup-\*`
do
  source $source
done

function_exists "setup_gitconfig" && setup_gitconfig
function_exists "setup_dotfiles" && setup_dotfiles
function_exists "setup_osx" && setup_osx
function_exists "setup_homebrew" && setup_homebrew

success "Setup complete"
