#!/bin/bash
#
# bootstrap installs things.

DOTFILES_SCRIPTS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DOTFILES_ROOT="$DOTFILES_SCRIPTS/.."

set -e

echo ''

info () {
  printf "\033[00;34m$1\033[0m\n"
}

user () {
  printf "\033[0;33m$1\033[0m: "
}

success () {
  printf "\033[00;32m$1\033[0m\n"
}

fail () {
  printf "\n\033[2K[\033[0;31mX\033[0m] $1\n"
  exit
}

for source in `find $DOTFILES_SCRIPTS -maxdepth 1 -name setup-\*`
do
  source $source
done

setup_gitconfig
setup_dotfiles
setup_osx
setup_homebrew

success "Setup complete"
