#!/bin/bash
#
# bootstrap installs things.

DOTFILES_SCRIPTS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DOTFILES_ROOT="$DOTFILES_SCRIPTS/.."

set -e

echo ''

info () {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

for source in `find $DOTFILES_SCRIPTS -maxdepth 1 -name setup-\*`
do
  source $source
done

setup_gitconfig
setup_dotfiles
# setup_osx
# setup_homebrew

success "Setup complete"
