#!/bin/bash
#
# This file is not run directly, it is instead called from script/bootstrap

setup_gitconfig () {
  if ! [ -f git/gitconfig.symlink ]
  then
    info 'Setting up gitconfig'

    user 'What is your github author name? '
    read -e git_authorname

    user 'What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" git/gitconfig.symlink.example > git/gitconfig.symlink

    success 'Setup gitconfig'
  fi
}
