#!/bin/bash
#
# This file is not run directly, it is instead called from script/bootstrap

setup_homebrew () {
  # If we are on a mac, lets install and setup homebrew
  if [ "$(uname -s)" == "Darwin" ]
  then
    info "Install homebrew things"
  fi
}


